### ISSUE TITLE
Waymo scene test 

### ISSUE THREAD

**Issue by FAM-vive** [kcheng1021/GaussianPro#13]
Thanks for your excellent work!
I follow the README to train gaussianpro on the Waymo dataset you provided, and I don't change any parameters, but i can't get same results as your paper showed, especially the rendered normal result, do you know why?

what i run:
![ours](https://github.com/kcheng1021/GaussianPro/assets/46038444/d09fdbd1-9d2b-4588-bed4-db2e8845d5a4)
what you show:
<img width="875" alt="paper" src="https://github.com/kcheng1021/GaussianPro/assets/46038444/ee6eee0f-d77a-49e3-af4e-b1f9ab629e76">

**Comment by kcheng1021** [comment]
Thank you for your recognition. Your results do seem similar to the baseline. I suspect there might be an issue with the line breaks in your bash file, i.e. \ in each line, causing the parameters to not be properly inputted.

**Comment by merriaux** [comment]
Hi @kcheng1021,
Many for this very interesting works.
I reached the same issue as @FAM-vive. I run it a second time with the train command on an unique line:
`python train.py -s my-data-path -m my-output-path --eval --flatten_loss --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 --dataset waymo --sky_seg --normal_loss --depth_loss --propagation_interval 30 --depth_error_min_threshold 0.8 --depth_error_max_threshold 1.0 --propagated_iteration_begin 1000 --propagated_iteration_after 12000 --patch_size 20 --lambda_l1_normal 0.001 --lambda_cos_normal 0.001`

![image](https://github.com/kcheng1021/GaussianPro/assets/16850602/955d3580-9196-4ed5-9ef0-a02e12334088)
![image](https://github.com/kcheng1021/GaussianPro/assets/16850602/536ec0ac-ecd5-451d-a4f1-defd559b6bed)
![image](https://github.com/kcheng1021/GaussianPro/assets/16850602/a957f104-32d5-4208-a756-ce79aca11ebd)

the metric are lower than what you published:
  "SSIM": 0.9529152512550354,
  "PSNR": 35.29518127441406,
  "LPIPS": 0.226970374584198

For information the metric of baseline: `python train.py -s my-data-path  -m my-output-path --eval --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 --dataset waymo `
are very close to ours:
SSIM :    0.9498498
PSNR :   35.0038567
LPIPS:    0.2342816

Clearly the normals rendering is really worst than ours. Do you have any idea of I am doing wrong ?
thanks

**Comment by kcheng1021** [comment]
Based on the current findings, it seems that the propagation process might not have been properly executed in your results. To better understand the situation and identify the underlying causes, it would greatly benefit the analysis if you could share the scene results from your training. 
Additionally, I would like to offer my assistance in other two ways: either by remotely connecting to your machine or by providing my contact information via email. (drop your email or other contact info to me) This will allow us to establish direct communication and solve the issue in the quickest possible manner. @FAM-vive @merriaux

**Comment by KizzySama** [comment]
@FAM-vive @merriaux 
I have met the similar problem as yours. It turns out that there is a mistake in my bash file just as @kcheng1021 mentioned. 

After I fixed it, I got the correct result as showed below:
![96be43ae99f29e1604c2db9b45896d04](https://github.com/kcheng1021/GaussianPro/assets/35948311/da394389-d643-479b-a16b-e969cd7829a8)

**Comment by merriaux** [comment]
Hi  @kcheng1021 and @KizzySama
Yes I used waymo sequence from your google drive link. I didn't notice any warning during training.
I will write you an email, and start upload of training results.

@KizzySama, could share with us the train cmd you use ? or have a look to the cmd I used in my first message ?
thanks

**Comment by KizzySama** [comment]
> Hi @kcheng1021 and @KizzySama Yes I used waymo sequence from your google drive link. I didn't notice any warning during training. I will write you an email, and start upload of training results.
> 
> @KizzySama, could share with us the train cmd you use ? or have a look to the cmd I used in my first message ? thanks

Your training command looks correct, maybe you need to check whether your propagation is up and running. My result looks like:
![96be43ae99f29e1604c2db9b45896d04](https://github.com/kcheng1021/GaussianPro/assets/35948311/420cf8c3-e2ab-4fab-bc4f-9df5b8dd3835)

**Comment by FAM-vive** [comment]
> Hi, @merriaux @FAM-vive. Perphas I found the reason. I specified the GPU architecture as sm86 in the CMakeLists.txt, but your GPUs may have a lower compute capability, which is why the propagation was not successful. Please replace it with a version that is suitable for your GPU.

@kcheng1021 , thanks so much! I have solved the problem by what you said, and then the propagation process executed successfully, and finally i get same results as your paper showed.
