### ISSUE TITLE
Which segmentation method did you use to get the sky seg mask?

### ISSUE THREAD

**Issue by yifanlu0227** [kcheng1021/GaussianPro#14]
Hi, thanks for your impressive work!

Could you direct a way to how you get the sky seg mask? The segmentation is fine and I want to use it on my data :)

**Comment by kcheng1021** [comment]
Hi, I use the segformer.b0.1024x1024.city.160k.pth. Here is the url. https://github.com/NVlabs/SegFormer

**Comment by yifanlu0227** [comment]
Thanks!
