### ISSUE TITLE
Interactive viewer

### ISSUE THREAD

**Issue by HungNgoCT** [kcheng1021/GaussianPro#16]
Hi.,

Thank you for great work.
Is there interactive viewer so that we can see results from any view points which is similar viewer in 3DGS?

**Comment by kcheng1021** [comment]
Hi, the original 3DGS viewer is supported.

**Comment by Ericgone** [comment]
hi, how do you preprocess your own data? Specifically, how did you get the 'Mask' folder?

**Comment by sngkhiem** [comment]
@HungNgoCT hi, I have something want to ask you, can i have your email?, i will say more detail in email

**Comment by Ericgone** [comment]
> @HungNgoCT hi, I have something want to ask you, can i have your email?, i will say more detail in email

hi, sure. glad to discuss something with you, my e-mail address is gjrscnu@126.com

**Comment by sngkhiem** [comment]
@Ericgone  sorry mate, i mean i have sth to discuss with @HungNgoCT

**Comment by HungNgoCT** [comment]
> @Ericgone sorry mate, i mean i have sth to discuss with @HungNgoCT

Sent you an email alreay
