### ISSUE TITLE
关于新增的cuda代码部分的问题

### ISSUE THREAD

**Issue by 520jz** [kcheng1021/GaussianPro#21]
作者您好，我发现您在源码里面添加了Propagation这部分cuda代码，我想问一下您是否也修改了Gaussian光栅化的那部分代码呢？就是diff-gaussian-rasterization这部分，我需要重新去安装这部分吗？还是说保持Gaussian原来的环境就行了

**Comment by kcheng1021** [comment]
diff-gaussian-rasterization is same as the 3DGS

**Comment by 520jz** [comment]
> diff-gaussian-rasterization is same as the 3DGS

哦哦哦，diff-gaussian-rasterization与原始的3DGS是相同的，谢谢作者！
