### ISSUE TITLE
Error： ModuleNotFoundError: No module named 'pcpr'

### ISSUE THREAD

**Issue by cv-lab-x** [kcheng1021/GaussianPro#4]
thanks for your great work, there's some errors when run the waymo demo,   some files may missing when build Propagation ?

`File "GaussianPro/utils/graphics_utils.py", line 16, in <module>
    import pcpr
ModuleNotFoundError: No module named 'pcpr'
`

Looking forward to your reply，thanks! @kcheng1021

**Comment by Disa-Kizonda** [comment]
https://github.com/wuminye/PCPR

**Comment by kcheng1021** [comment]
Apologies for this. The code about 'pcpr' was part of my experimental attempts. Please feel free to remove the relevant packages and codes directly.

**Comment by cv-lab-x** [comment]
> Apologies for this. The code about 'pcpr' was part of my experimental attempts. Please feel free to remove the relevant packages and codes directly.

thanks for your quick reply, another Error:
`FileNotFoundError: [Errno 2] No such file or directory: './cache/propagated_depth/costs.dmb'`

Looking forward for your reply, thanks! @kcheng1021

**Comment by kcheng1021** [comment]
Does the path './cache/propagated_depth/' exists in your project? Could you offer the full information about the error?

**Comment by cv-lab-x** [comment]
> Does the path './cache/propagated_depth/' exist in your project? Could you offer the complete print about the error?

ye, the dir exists. 

`Loading Test Cameras [02/03 19:59:21]
Number of points at initialisation :  72378 [02/03 19:59:23]
Training progress:   0%|                                                                                                                                                                                                     | 0/30000 [00:00<?, ?it/s]
[ITER 1] Evaluating test: L1 0.20549551770091057 PSNR 11.761059880256653 [02/03 19:59:27]

[ITER 1] Evaluating train: L1 0.232677760720253 PSNR 10.858474922180177 [02/03 19:59:31]

[ITER 1] Saving Gaussians [02/03 19:59:31]
Training progress:   3%|█████▋                                                                                                                                                                    | 1010/30000 [01:21<34:26, 14.03it/s, Loss=0.3947600]terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) ./modules/core/src/matrix_expressions.cpp:24: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

Aborted (core dumped)
Traceback (most recent call last):
  File "train.py", line 372, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 129, in training
    propagated_depth, cost, normal = read_propagted_depth('./cache/propagated_depth')
  File "GaussianPro/utils/general_utils.py", line 244, in read_propagted_depth
    cost = readDepthDmb(os.path.join(path, 'costs.dmb'))
  File "GaussianPro/utils/general_utils.py", line 192, in readDepthDmb
    inimage = open(file_path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './cache/propagated_depth/costs.dmb'
Training progress:   3%|█████▋                                                                                                                                                                    | 1010/30000 [01:22<39:18, 12.29it/s, Loss=0.3947600]
Looking for config file in output/gs_pro/cfg_args
`

**Comment by kcheng1021** [comment]
I haven't encountered this error on my server, and I guess it may be related to the specific versions of the environment. I will try to reproduce this error later. For now, I'll provide some information about the computer I'm testing on: Ubuntu 20.04.1 LTS, GeForce 3090. As for the versions of OpenCV, for opencv-python, our version is 4.9.0.80. For opencv for C++ in the Propagation module, our version is 4.2.0.

**Comment by cv-lab-x** [comment]
> './cache/propagated_depth/costs.dmb'

thanks for your reply,  the file "'./cache/propagated_depth/costs.dmb'" needs to be preprocessed or it'll be generated by the training process,    cause there's no './cache/propagated_depth/costs.dmb' file in the origin codes

looking forward to your reply, thanks! @kcheng1021

**Comment by GongMingCarmen** [comment]
@cv-lab-x  "I encountered the same issue, how did you solve it?"

**Comment by Valkyrie1215** [comment]
+1, there is no "costs.dmb"file in the './cache/propagated_depth',hasn't it been uploaded yet?
![image](https://github.com/kcheng1021/GaussianPro/assets/104125743/2ea86ac6-188a-4f85-872b-3b97dfda534b)

**Comment by cv-lab-x** [comment]
> @cv-lab-x "I encountered the same issue, how did you solve it?"

not yet

**Comment by kcheng1021** [comment]
These files are generated during the execution of the propagation process rather than pre-existing. It's possible that an error occurred during the propagation steps. Could you please provide your hardware and environment information? I will try to reproduce the bug.

**Comment by kcheng1021** [comment]
This issue about 'pcpr' has been solved. To help others better get the related information. I would like to merge your further questions with Issue #8.

**Comment by cv-lab-x** [comment]
> This issue about 'pcpr' has been solved. To help others better get the related information. I would like to merge your further questions with Issue #8.

i have fixed the bugs, and add a PR to fixing it

**Comment by kcheng1021** [comment]
> > This issue about 'pcpr' has been solved. To help others better get the related information. I would like to merge your further questions with Issue #8.
> 
> i have fixed the bugs, and add a PR to fixing it

Thanks for your debuging and help! But we found why the ref_id 0 is not be passed. Please refer to Issue https://github.com/kcheng1021/GaussianPro/issues/8
