### ISSUE TITLE
No such file or directory: '.\\cache\\propagated_depth\\costs.dmb'

### ISSUE THREAD

**Issue by hanhantie233** [kcheng1021/GaussianPro#42]
Code:`python train.py -s D:\01ZPS_data\datasets\F -m output\F --eval --flatten_l
oss --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 --dataset waymo --normal_loss --depth_loss --propagation_interval 30 --dept
h_error_min_threshold 0.8 --depth_error_max_threshold 1.0 --propagated_iteration_begin 1000 --propagated_iteration_after 12000 --patch_size 20 --lambda_l1_normal
 0.001 --lambda_cos_normal 0.001 --data_device cpu
`

`Traceback (most recent call last):
  File "train.py", line 373, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint,
 args.debug_from)
  File "train.py", line 129, in training
    propagated_depth, cost, normal = read_propagted_depth('.\\cache\\propagated_depth')
  File "D:\01ZPS_data\models\GaussianPro\utils\general_utils.py", line 246, in read_propagted_depth
    cost = readDepthDmb(os.path.join(path, 'costs.dmb'))
  File "D:\01ZPS_data\models\GaussianPro\utils\general_utils.py", line 192, in readDepthDmb
    inimage = open(file_path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '.\\cache\\propagated_depth\\costs.dmb'
Training progress:   3%|██▊ `
![image](https://github.com/kcheng1021/GaussianPro/assets/130548715/545b581f-a76b-4ada-84b6-6a03b10c93b2)

How to get these files?

**Comment by kcheng1021** [comment]
Hi, you could refers to Issue #8 . Seems your propagation module does not run correctly.
