### ISSUE TITLE
terminate called after throwing an instance of 'cv::Exception'

### ISSUE THREAD

**Issue by rkdckddnjs9** [kcheng1021/GaussianPro#5]
Thank u for your excellent work!

i got a error as following

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) /home/opencv-4.2.0/modules/core/src/matrix_expressions.cpp:23: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

Aborted (core dumped)
Training progress:   8%|__                    | 2460/30000 [06:05<1:23:21,  5.51it/s, Loss=0.2444826$
  
  so i want to know what is the version of opencv about your environments
  
  thanks~ :)

**Comment by kcheng1021** [comment]
For the opencv-python, our version is 4.9.0.80. For the opencv for C++ in Propagation module, our version is 4.2.0. Hope this help you.

**Comment by rkdckddnjs9** [comment]
> For the opencv-python, our version is 4.9.0.80. For the opencv for C++ in Propagation module, our version is 4.2.0. Hope this help you.

Thanks for your reply :)

**Comment by rkdckddnjs9** [comment]
Thanks @kcheng1021 :)
