### ISSUE TITLE
RunError

### ISSUE THREAD

**Issue by JohnnyKimura** [kcheng1021/GaussianPro#52]
您好，我在pip 安装submodels中的三个对应模块时都出现了如下问题。我尝试修改我自己的cuda版本到11.6，发现还是出现这个问题，请问有什么解决办法吗，非常感谢！
![图片](https://github.com/kcheng1021/GaussianPro/assets/79315612/0e7f5e13-0072-462f-8ad6-9a7668e89cc5)
![图片](https://github.com/kcheng1021/GaussianPro/assets/79315612/c96652d9-4d44-47fd-8c48-c1534e84df9e)

**Comment by kcheng1021** [comment]
You could follow the environment setup in 3DGS first. Then adding the additional package in our project. It seems there are mismatching in CUDA version, (maybe the conflict is from /usr/local/cuda in .bashrc and the pytorch, cudatoolkit in your conda env? I am not sure about this). 

But at least our modification has no conflict with the original 3DGS. So maybe you can make sure 3DGS is loaded successfully, such as the diff_gaussian_rasterization module can be installed correctly.

**Comment by JohnnyKimura** [comment]
hi there,i really appreciate your amazing work. according to my problem，i have tried to change the version of CUDA from 12.0 to 11.6，but it encounter the same question. i ran the code on our sever station and there are no other authority for me to do more things，so change the cuda version is the least i can do according to the environment.yml .
so i start to think maybe the problem comes from environment setup. i try to create virtual environment on my sever station by using the pytorch and cuda toolkit that satisfy my CUDA 12.0，it did work when i pip" diff-gaussian "and "simple-knn"，but it still encount the same problem like the pics up there when i tried to pip "propagation" module. i have tried to fix the problem a whole afternoon tody,but still got no clues.
sorry again to bother u again，i would be so grateful to your reply

**Comment by kcheng1021** [comment]
Sorry to hear that. 
Based on your CUDA 12.0,  have you changed the 'include_dir' in setup.py of Propagation to adapt to your CUDA path?

**Comment by JohnnyKimura** [comment]
Hi there，i did modify it ，but dont know whether it can recognize my path or not. 😂，but when i modify it and ran the code it still encounter the same problem.. any suggestion？ maybe i will tried again tomorrow😫😰

**Comment by kcheng1021** [comment]
What is your pytorch version? The error seems saying the cuda mismatching from include path and the version compile pytorch.

**Comment by JohnnyKimura** [comment]
i tried the environment.yml and downgrade the version of my CUDA from 12.0 to 11.6 ，encounter the problem above，maybe my installation of cuda 11.6 is wrong . 
But i also tried to download pytorch that support cuda 12.0（according to https://pytorch.org/） it still remain the same ，a little bit confused and frustrated today ， but i will try again to figure it out

**Comment by JohnnyKimura** [comment]
Hi there ，i try to figure out my problem last night i mentioned ，but still encounter the same situation when i pip “propagation”  module
this is the problem i met （only present the error but ignore the warning）
![图片](https://github.com/kcheng1021/GaussianPro/assets/79315612/29043b31-1e00-4608-a018-3fbac5912f9e)

this is my virtual env setup：
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotli-python             1.0.9            py39h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2024.6.2         py39h06a4308_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.5                          3    nvidia
diff-gaussian-rasterization 0.0.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1           py39h06a4308_0  
freetype                  2.12.1               h4a9f257_0  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py39heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
idna                      3.7              py39h06a4308_0  
imageio                   2.34.1                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.1.4            py39h06a4308_0  
jpeg                      9e                   h5eee18b_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.10.0.4                      0    nvidia
libcurand                 10.3.6.39                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libwebp-base              1.3.2                h5eee18b_0  
llvm-openmp               14.0.6               h9e868ea_0  
lz4-c                     1.9.4                h6a678d5_1  
markupsafe                2.1.3            py39h5eee18b_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0            py39h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1            py39h06a4308_0  
numpy                     1.24.3           py39h14f4228_0  
numpy-base                1.24.3           py39h31eccc5_0  
opencv-python             4.9.0.80                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1w               h7f8727e_0  
pillow                    10.3.0           py39h5eee18b_0  
pip                       24.0             py39h06a4308_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.0                hdb3f193_2  
pytorch                   2.1.0           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0.1            py39h5eee18b_0  
readline                  8.2                  h5eee18b_0  
requests                  2.32.2           py39h06a4308_0  
setuptools                69.5.1           py39h06a4308_0  
simple-knn                0.0.0                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.12             py39h06a4308_0  
tk                        8.6.14               h39e8969_0  
torchaudio                2.1.0                py39_cu118    pytorch
torchtriton               2.1.0                      py39    pytorch
torchvision               0.16.0               py39_cu118    pytorch
typing_extensions         4.11.0           py39h06a4308_0  
tzdata                    2024a                h04d1e81_0  
urllib3                   2.2.1            py39h06a4308_0  
wheel                     0.43.0           py39h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2  


dont know what to do know ，no clues

**Comment by JohnnyKimura** [comment]
Hi there，i strictly follow your environment.yaml and downgrade my cuda to 11.7，i successfully install the submodules，but when i run the bash.sh (waymo scene)，i encounter a problem：
ImportError: /home/stlyj/.conda/envs/gaussianpro/lib/python3.7/site-packages/gaussianpro.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv5errorEiRKSsPKcS3_i
![image](https://github.com/kcheng1021/GaussianPro/assets/79315612/c9f2c617-ee8d-49f2-8acf-3482334809f8)


i search the solution but find little helpful answer， they cant solve my problem for now：（i have tried opencv ver from 4.2 to 4.5.5，i even tried 3.9.5，same problem）
https://forum.opencv.org/t/undefined-symbol-zn2cv5erroreirksspkcs3-i/8050

any suggestion？thanks for your kind reply
@kcheng1021

**Comment by kcheng1021** [comment]
It seems that your machine is not dynamically linked to the OpenCV library or there is a version mismatch, resulting in the missing CV-related dependencies. You can try linking to the OpenCV library in the Conda environment (conda install -c conda-forge opencv) instead of the system-installed OpenCV library obtained through apt install.

**Comment by JohnnyKimura** [comment]
thank u for your patient reply，after months of trying i finally run the code successfully for now
@kcheng1021

**Comment by JohnnyKimura** [comment]
thank u for your patient reply，after months of trying i finally run the code successfully for now
@kcheng1021
