### ISSUE TITLE
Question on modeling water

### ISSUE THREAD

**Issue by Gatswei** [kcheng1021/GaussianPro#6]
Thank u for your excellent work!
I train gaussianpro in the park scene. The output rendering is well aligned with the geometry. But I find that the water geometry doesn't look very good. Do you have any ideas to improve this aspect in the future?
![00012](https://github.com/kcheng1021/GaussianPro/assets/92842765/46609f52-ad15-4ab7-afba-b1ea29b84897)
![00012normal](https://github.com/kcheng1021/GaussianPro/assets/92842765/5294843b-10e1-434b-9a8b-b007485965ff)

**Comment by kcheng1021** [comment]
Thank you for your attention. The water not only lacks texture, but also presents challenges such as reflections and specular effects. Its color varies under different viewpoints, requiring additional modeling. This could be a promising research direction in the future.
