### ISSUE TITLE
Question about waymo data

### ISSUE THREAD

**Issue by rkdckddnjs9** [kcheng1021/GaussianPro#7]
Thanks for your excellent works!!

I just have question about waymo!

How can i generate the data format like your drive link? (ex. sky_mask, sparse/0/points3D.ply)

Thanks for reading :)

**Comment by kcheng1021** [comment]
Hi, thanks for your attention. sky_mask is generated by SegFormer. points3D.ply is generated during runing GaussianPro.

**Comment by rkdckddnjs9** [comment]
> Hi, thanks for your attention. sky_mask is generated by SegFormer. points3D.ply is generated during runing GaussianPro. You only need points3D.bin.

Thanks for your reply!!
Was the SegFormer model trained on ADE20K used to create a sky mask?
Does "points3D.bin" refer to Structure from Motion (SfM) points?

**Comment by kcheng1021** [comment]
1. I use the segformer.b0.1024x1024.city.160k.pth. Acutally sky mask is not used in training. I just use it to better visualize the depth and normal map.
2.  Yes.
