### ISSUE TITLE
Colmap pointcloud

### ISSUE THREAD

**Issue by qianfanshen** [kcheng1021/GaussianPro#70]
Thanks again for your amazing work！i wonder what's the arguments you used to generate the SFM pointcloud by using convert.py since when i used the default convert.py on images from segment102751 you provided, only 2 images and 159 points were left, and were distorted

**Comment by kcheng1021** [comment]
Hi, I found the command line of colmap tends to crush. You could use the GUI of colmap (I use the version 3.8 ) to generate the scenes. (automatic reconstruction is ok. Remeber to choose the Pinhole camera model, or you need to undistort the images.)
