### ISSUE TITLE
No module named 'gaussianpro'

### ISSUE THREAD

**Issue by z-x-j** [kcheng1021/GaussianPro#73]
您好，这个gaussianpro的库是需要自己安装吗？ 
 File "/data/zxj/3dgs/GaussianPro/utils/graphics_utils.py", line 18, in <module>
    from gaussianpro import propagate
ModuleNotFoundError: No module named 'gaussianpro'

**Comment by YunzhuMeng** [comment]
您好，想问下您后来解决了吗
